export default {
  carauselInfo: [],
  popularMovies: [],
  popularTvShows: [],
  recommendationMovie: [],
  recommendationTv: [],
  recommendationDetail: [],
  upcomingTrailers: [],
  upcomingTrailersDefaultUrl: "",
  videoUrl: "",
  detail: [],
  season: [],
  person: [],
  allMovies: [],
  allData:[],
  loadMoreData: [],
  search: [],
  wlist: [],
};
