export const MovieCategoryList = [
  {
    title: "Action",
    description: "Action",
    alt: "Action",
    id: 28,
  },
  {
    title: "Adventure",
    description: "Adventure",
    alt: "Adventure",
    id: 12,
  },
  {
    title: "Animation",
    description: "Animation",
    alt: "Animation",
    id: 16,
  },
  {
    title: "Comedy",
    description: "Comedy",
    alt: "Comedy",
    id: 35,
  },
  {
    title: "Crime",
    description: "Crime",
    alt: "Crime",
    id: 80,
  },
  {
    title: "Documentary",
    description: "Documentary",
    alt: "Documentary",
    id: 99,
  },
  {
    title: "Drama",
    description: "Drama",
    alt: "Drama",
    id: 18,
  },
  {
    title: "Family",
    description: "Family",
    alt: "Family",
    id: 10751,
  },
  {
    title: "Fantasy",
    description: "Fantasy",
    alt: "Fantasy",
    id: 14,
  },
  {
    title: "History",
    description: "History",
    alt: "History",
    id: 36,
  },
  {
    title: "Horror",
    description: "Horror",
    alt: "Horror",
    id: 27,
  },
  {
    title: "Music",
    description: "Music",
    alt: "Music",
    id: 10402,
  },
  {
    title: "Mystery",
    description: "Mystery",
    alt: "Mystery",
    id: 9648,
  },
  {
    title: "Romance",
    description: "Romance",
    alt: "Romance",
    id: 10749,
  },
  {
    title: "Science Fiction",
    description: "Science Fiction",
    alt: "Science Fiction",
    id: 878,
  },
  {
    title: "Thriller",
    description: "Thriller",
    alt: "Thriller",
    id: 53,
  },
  {
    title: "War",
    description: "War",
    alt: "War",
    id: 10752,
  },
  {
    title: "TV Movie",
    description: "TV Movie",
    alt: "TV Movie",
    id: 10770,
  },
  {
    title: "Western",
    description: "Western",
    alt: "Western",
    id: 37,
  },
  {
    title: "Popular",
    description: "popular",
    alt: "popular",
  },
  {
    title: "Now Playing",
    description: "now_playing",
    alt: "Now Playing",
  },
  {
    title: "Top Rated",
    description: "top_rated",
    alt: "Top Rated",
  },
  {
    title: "Upcoming",
    description: "upcoming",
    alt: "upcoming",
  },
];
