export const quotes = [
  { quotes: "Frankly, my dear, I don't give a damn.", movieName: "Gone With the Wind" ,year:'1939'},
  { quotes: "I'm going to make him an offer he can't refuse.", movieName: "The Godfather" ,year:'1972'},
  { quotes: "You don't understand! I coulda had class. I coulda been a contender. I could've been somebody, instead of a bum, which is what I am.", movieName: " On the Waterfront," ,year:'1954'},
  { quotes: "Toto, I've got a feeling we're not in Kansas anymore.", movieName: "The Wizard of Oz" ,year:'1939'},
  { quotes: "Here's looking at you, kid.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "Go ahead, make my day.", movieName: "Sudden Impact" ,year:'1983'},
  { quotes: "All right, Mr. DeMille, I'm ready for my close-up.", movieName: "Sunset Boulevard" ,year:'1950'},
  { quotes: "May the Force be with you.", movieName: "Star Wars" ,year:'1977'},
  { quotes: "Fasten your seatbelts. It's going to be a bumpy night.", movieName: "All About Eve" ,year:'1950'},
  { quotes: "You talking to me?", movieName: "Taxi Driver" ,year:'1976'},
  { quotes: "What we've got here is failure to communicate.", movieName: "Cool Hand Luke" ,year:'1967'},
  { quotes: "I love the smell of napalm in the morning.", movieName: "Apocalypse Now" ,year:'1979'},
  { quotes: "Love means never having to say you're sorry.", movieName: "Love Story" ,year:'1970'},
  { quotes: "The stuff that dreams are made of.", movieName: "The Maltese Falcon" ,year:'1941'},
  { quotes: "E.T. phone home.", movieName: "E.T. The Extra-Terrestrial" ,year:'1982'},
  { quotes: "They call me Mister Tibbs!", movieName: "In the Heat of the Night" ,year:'1967'},
  { quotes: "Rosebud.", movieName: "Citizen Kane" ,year:'1941'},
  { quotes: "Made it, Ma! Top of the world!", movieName: "White Heat" ,year:'1949'},
  { quotes: "I'm as mad as hell, and I'm not going to take this anymore!", movieName: "Network" ,year:'1976'},
  { quotes: "Louis, I think this is the beginning of a beautiful friendship.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "A census taker once tried to test me. I ate his liver with some fava beans and a nice Chianti.", movieName: "The Silence of the Lambs" ,year:'1991'},
  { quotes: "Bond. James Bond.", movieName: "Dr. No" ,year:'1962'},
  { quotes: "There's no place like home.", movieName: "The Wizard of Oz" ,year:'1939'},
  { quotes: "I am big! It's the pictures that got small.", movieName: "Sunset Blvd" ,year:'1950'},
  { quotes: "Show me the money!", movieName: "Jerry Maguire" ,year:'1996'},
  { quotes: "Why don't you come up sometime and see me?", movieName: "She Done Him Wrong" ,year:'1933'},
  { quotes: "I'm walking here! I'm walking here!", movieName: "Midnight Cowboy" ,year:'1969'},
  { quotes: "Play it, Sam. Play 'As Time Goes By.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "You can't handle the truth!", movieName: "A Few Good Men" ,year:'1992'},
  { quotes: "I want to be alone.", movieName: "Grand Hotel" ,year:'1932'},
  { quotes: "After all, tomorrow is another day!", movieName: "Gone With the Wind" ,year:'1939'},
  { quotes: "Round up the usual suspects.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "I'll have what she's having.", movieName: " When Harry Met Sally" ,year:'1989'},
  { quotes: "You know how to whistle, don't you, Steve? You just put your lips together and blow.", movieName: "To Have and Have Not" ,year:'1944'},
  { quotes: "You're gonna need a bigger boat.", movieName: "Jaws" ,year:'1975'},
  { quotes: "Badges? We ain't got no badges! We don't need no badges! I don't have to show you any stinking badges!", movieName: "The Treasure of the Sierra Madre" ,year:'1948'},
  { quotes: "I'll be back.", movieName: "The Terminator" ,year:'1984'},
  { quotes: "Today, I consider myself the luckiest man on the face of the earth.", movieName: "The Pride of the Yankees" ,year:'1942'},
  { quotes: "If you build it, he will come.", movieName: "Field of Dreams" ,year:'1989'},
  { quotes: "Mama always said life was like a box of chocolates. You never know what you're gonna get.", movieName: "Forrest Gump" ,year:'1994'},
  { quotes: "We rob banks.", movieName: "Bonnie and Clyde" ,year:'1967'},
  { quotes: "Plastics.", movieName: "The Graduate" ,year:'1967'},
  { quotes: "We'll always have Paris.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "I see dead people.", movieName: "The Sixth Sense" ,year:'1999'},
  { quotes: "Stella! Hey, Stella!", movieName: "A Streetcar Named Desire" ,year:'1951'},
  { quotes: "Oh, Jerry, don't let's ask for the moon. We have the stars.", movieName: "Now, Voyager" ,year:'1942'},
  { quotes: "Shane. Shane. Come back!", movieName: "Shane" ,year:'1953'},
  { quotes: "Well, nobody's perfect.", movieName: "Some Like It Hot" ,year:'1959'},
  { quotes: "It's alive! It's alive!", movieName: "Frankenstein" ,year:'1931'},
  { quotes: "Houston, we have a problem.", movieName: "Apollo 13" ,year:'1995'},
  { quotes: "You've got to ask yourself one question: 'Do I feel lucky?' Well, do ya, punk?", movieName: " Dirty Harry" ,year:'1971'},
  { quotes: "You had me at ?hello.?", movieName: "Jerry Maguire" ,year:'1996'},
  { quotes: "One morning I shot an elephant in my pajamas. How he got in my pajamas, I don't know.", movieName: "Animal Crackers" ,year:'1930'},
  { quotes: "There's no crying in baseball!", movieName: " A League of Their Own" ,year:'1992'},
  { quotes: "La-dee-da, la-dee-da.", movieName: "Annie Hall" ,year:'1977'},
  { quotes: "A boy's best friend is his mother.", movieName: "Psycho" ,year:'1960'},
  { quotes: "Greed, for lack of a better word, is good.", movieName: "Wall Street" ,year:'1987'},
  { quotes: "Keep your friends close, but your enemies closer.", movieName: "The Godfather Part II" ,year:'1974'},
  { quotes: "As God is my witness, I'll never be hungry again.", movieName: "Gone With the Wind" ,year:'1939'},
  { quotes: "Well, here's another nice mess you've gotten me into!", movieName: "Sons of the Desert" ,year:'1933'},
  { quotes: "Say 'hello' to my little friend!", movieName: "Scarface" ,year:'1983'},
  { quotes: "What a dump.", movieName: "Beyond the Forest" ,year:'1949'},
  { quotes: "Mrs. Robinson, you're trying to seduce me. Aren't you?", movieName: "The Graduate" ,year:'1967'},
  { quotes: "Gentlemen, you can't fight in here! This is the War Room!", movieName: "Dr. Strangelove" ,year:'1964'},
  { quotes: "Elementary, my dear Watson.", movieName: "The Adventures of Sherlock Holmes" ,year:'1929'},
  { quotes: "Get your stinking paws off me, you damned dirty ape.", movieName: "Planet of the Apes" ,year:'1968'},
  { quotes: "Of all the gin joints in all the towns in all the world, she walks into mine.", movieName: "Casablanca" ,year:'1942'},
  { quotes: "Here's Johnny!", movieName: "The Shining" ,year:'1980'},
  { quotes: "They're here!", movieName: "Poltergeist" ,year:'1982'},
  { quotes: "Is it safe?", movieName: "Marathon Man" ,year:'1976'},
  { quotes: "Wait a minute, wait a minute. You ain't heard nothin' yet!", movieName: "The Jazz Singer" ,year:'1927'},
  { quotes: "No wire hangers, ever!", movieName: "Mommie Dearest" ,year:'1981'},
  { quotes: "Mother of mercy, is this the end of Rico?", movieName: "Little Caesar" ,year:'1930'},
  { quotes: "Forget it, Jake, it's Chinatown.", movieName: "Chinatown" ,year:'1974'},
  { quotes: "I have always depended on the kindness of strangers.", movieName: "A Streetcar Named Desire" ,year:'1951'},
  { quotes: "Hasta la vista, baby.", movieName: "Terminator 2: Judgment Day" ,year:'1991'},
  { quotes: "Soylent Green is people!", movieName: "Soylent Green" ,year:'1973'},
  { quotes: "Open the pod bay doors, HAL.", movieName: "2001: A Space Odyssey" ,year:'1968'},
  { quotes: "Yo, Adrian!", movieName: "Rocky II" ,year:'1979'},
  { quotes: "Hello, gorgeous.", movieName: "Funny Girl" ,year:'1968'},
  { quotes: "Toga! Toga!", movieName: "National Lampoon's Animal House" ,year:'1978'},
  { quotes: "Listen to them. Children of the night. What music they make.", movieName: "Dracula" ,year:'1931'},
  { quotes: "Oh, no, it wasn't the airplanes. It was Beauty killed the Beast.", movieName: "King Kong" ,year:'1933'},
  { quotes: "My precious.", movieName: "The Lord of the Rings: Two Towers" ,year:'2002'},
  { quotes: "Attica! Attica!", movieName: "Dog Day Afternoon" ,year:'1975'},
  { quotes: "Sawyer, you're going out a youngster, but you've got to come back a star!", movieName: "42nd Street" ,year:'1933'},
  { quotes: "Tell 'em to go out there with all they got and win just one for the Gipper.", movieName: "Knute Rockne All American" ,year:'1940'},
  { quotes: "A martini. Shaken, not stirred.", movieName: "Goldfinger" ,year:'1964'},
  { quotes: "Who's on first.", movieName: "The Naughty Nineties" ,year:'1945'},
  { quotes: "Life is a banquet, and most poor suckers are starving to death!", movieName: "Auntie Mame" ,year:'1958'},
  { quotes: "I feel the need - the need for speed!", movieName: "Top Gun" ,year:'1986'},
  { quotes: "Carpe diem. Seize the day, boys. Make your lives extraordinary.", movieName: "Dead Poets Society" ,year:'1989'},
  { quotes: "Snap out of it!", movieName: "Moonstruck" ,year:'1987'},
  { quotes: "My mother thanks you. My father thanks you. My sister thanks you. And I thank you.", movieName: "Yankee Doodle Dandy" ,year:'1942'},
  { quotes: "Nobody puts Baby in a corner", movieName: "Dirty Dancing" ,year:'1987'},
  { quotes: "I'll get you, my pretty, and your little dog, too!", movieName: "The Wizard of Oz" ,year:'1939'},
  { quotes: "I'm king of the world!", movieName: "Titanic" ,year:'1997'},
  { quotes: "You make me want to be a better man.", movieName: "As Good As It Gets" ,year:'1997'},
  { quotes: "The Dude abides.", movieName: "The Big Lebowski" ,year:'1998'},
  { quotes: "They call it a Royale with cheese.", movieName: "Pulp Fiction" ,year:'1994'}
];